### PR TITLE
Kaan Tek updated info.txt

### PR DESCRIPTION
**Pull request by KaanTekTr**
Kaan Tek updated info.txt

### CODE REVIEW

**Comment by PermanAtayev** [comment]
Hey, I merged your text, there was a conflict therefore it will be seen as rejected. Just take a screenshot of info.txt and you will be good to go.

**Comment by KaanTekTr** [comment]
Okey will do. But just for the learning purposes, may I ask what caused the
conflict?

Thanks.

**Comment by PermanAtayev** [comment]
The reason is that everyone is writing to the same file. Now for example
you write to info.txt at line 7 and someone else forks at the same time you
do and also adds her name to the same line. Therefore, when you both send
me a pull request git doesn't know which one should actually go to the 7th
line.

Best,
Perman

**Comment by KaanTekTr** [comment]
Okay, I understand now.

Thanks a lot.

**Pull request closed without merging**
